# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyaws < Formula
  desc "Terminal UI for browsing AWS resources"
  homepage "https://github.com/bkneis/lazyaws"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bkneis/lazyaws/releases/download/v0.0.4/lazyaws_0.0.4_darwin_amd64.tar.gz"
      sha256 "9c0dbd406ce8dc7c48d37ed98033c87cd33a84e99c50f8fa0438633d03286d7f"

      define_method(:install) do
        bin.install "lazyaws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bkneis/lazyaws/releases/download/v0.0.4/lazyaws_0.0.4_darwin_arm64.tar.gz"
      sha256 "978088b5ec1e006457caa5b0460c8f2a8e0bf876b7b63421c9b40a6c828a84c7"

      define_method(:install) do
        bin.install "lazyaws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkneis/lazyaws/releases/download/v0.0.4/lazyaws_0.0.4_linux_amd64.tar.gz"
      sha256 "6dc0f21855d8fbd70700ee1e8dcbddba3a9090023b34bfa1797e9d647e1c29bf"
      define_method(:install) do
        bin.install "lazyaws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkneis/lazyaws/releases/download/v0.0.4/lazyaws_0.0.4_linux_arm64.tar.gz"
      sha256 "49eb4d380d7ebfe81cd04a0b00d78f58ade2b9e903e1815157d3e50977917c7a"
      define_method(:install) do
        bin.install "lazyaws"
      end
    end
  end

  test do
    system "#{bin}/lazyaws", "--version"
  end
end
