# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyaws < Formula
  desc "Terminal UI for browsing AWS resources"
  homepage "https://github.com/bkneis/lazyaws"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bkneis/lazyaws/releases/download/v0.0.5/lazyaws_0.0.5_darwin_amd64.tar.gz"
      sha256 "6ef35a02623b85e7ab6660f76ac8c7a97a262bd1295cd8554a0aae87a1df3fde"

      define_method(:install) do
        bin.install "lazyaws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bkneis/lazyaws/releases/download/v0.0.5/lazyaws_0.0.5_darwin_arm64.tar.gz"
      sha256 "852bfe73466f42cef05f2ca5f16a847ade216e9bbeb9dcebb7a2ca4573869061"

      define_method(:install) do
        bin.install "lazyaws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkneis/lazyaws/releases/download/v0.0.5/lazyaws_0.0.5_linux_amd64.tar.gz"
      sha256 "e4adb0cd44556f83411f02f72d51ba5822f7579b06ad72a7f0032cee4fa97238"
      define_method(:install) do
        bin.install "lazyaws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bkneis/lazyaws/releases/download/v0.0.5/lazyaws_0.0.5_linux_arm64.tar.gz"
      sha256 "95bb6dae952dfa8cf29f7450e620261feec2ebdc24bda3a2ef60d829060cb203"
      define_method(:install) do
        bin.install "lazyaws"
      end
    end
  end

  test do
    system "#{bin}/lazyaws", "--version"
  end
end
